image:
  registry: docker.io
  repository: mediawiki
  tag: latest #1.34.0-debian-10-r31
  pullPolicy: IfNotPresent

mediawikiUser: user
mediawikiDB: mediadb
mediawikiDBUser: sunil
mediawikiDBPass: pass123

mediawikiEmail: user@example.com
mediawikiName: My Wiki
allowEmptyPassword: "yes"
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
