---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "demo.fullname" . }}-mediawiki-db
spec:
  selector:
    matchLabels:
      app: mediawiki-db
  replicas: 1
  template:
    metadata:
      labels:
        chart: {{ template "demo.fullname" . }}
        app: mediawiki-db
    spec:
      containers:
        - name: mediawiki-db-container
          image: mariadb
          env:
            - name: MYSQL_DATABASE
              value: my_wiki
            - name: MYSQL_USER
              value: wikiuser
            - name: MYSQL_PASSWORD
              value: example
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: 'yes'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "demo.fullname" . }}-mediawiki-app
spec:
  selector:
    matchLabels:
      app: mediawiki-app
  replicas: 2
  template:
    metadata:
      labels:
        chart: {{ template "demo.fullname" . }}
        app: mediawiki-app
    spec:
      containers:
        - name: mediawiki-container
          image: vistasunil/mediawiki:v4
          volumeMounts:
            - mountPath: /var/www/html/images
              name: mediawiki-volume
              #           - mountPath: /phpfile/LocalSettings.php
                  #  name: phpmount
              #- mountPath: /var/www/html/LocalSettings.php
              #name: mediawiki-localsettings
              #       subPath: LocalSettings.php
              #command: ["/bin/cp /phpfile/LocalSettings.php /var/www/html/LocalSettings.php"]
          ports:
            - containerPort: 80
      volumes:
        - name: mediawiki-volume
          #- name: phpmount
          #hostPath:
          #  path: /home/ubuntu/mediawiki/phpfile/LocalSettings.php
          #  type: FileOrCreate #Directory #OrCreate
            #- hostPath:
            #path: /home/ubuntu/mediawiki/phpfile/LocalSettings.php
            #type: FileOrCreate
            # name: mediawiki-localsettings
